### ISSUE TITLE
Quick question about your prompt 

### ISSUE THREAD

**Issue by shi-kejian** [sail-sg/Cheating-LLM-Benchmarks#1]
Hi, 

Thanks for this great work. 

I just wanted to have a quick clarification/confirmation: 

Based on your Figure 8 and Figure 9 (appendix), it seems like we don't need to handle the swapping position WITHIN the adversarial injection, right? 

![Screenshot 2024-10-18 at 1 51 15 AM](https://github.com/user-attachments/assets/790e1df9-5c8f-4e1b-8fa1-05e3929d67c9)

So in the jailbreak, we always have system "M" and then system "m" (See pic above), regardless of the position for `target preference`.

Thank you!

**Comment by xszheng2020** [comment]
Hi, @shi-kejian 

Thanks for your interest in our work.

Yes, you don't need to handle the swapping position.

As mentioned in the Section 3 of the paper: 

> The response is carefully structured to be resilient against swap operations.
